[package]
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
name = "fe-compiler-tests-legacy"
version = "0.24.0"
license = "GPL-3.0-or-later"
repository = "https://github.com/ethereum/fe"

[dependencies]

[dev-dependencies]
ethabi = { default-features = false, version = "18.0" }
evm = { default-features = false, version = "0.37" }
evm-runtime = { default-features = false, version = "0.37" }
fe-analyzer = {path = "../analyzer", version = "^0.24.0"}
fe-common = {path = "../common", version = "^0.24.0"}
fe-compiler-test-utils = {path = "../test-utils" }
fe-parser = {path = "../parser", version = "^0.24.0"}
fe-yulc = {path = "../yulc", version = "^0.24.0"}
fe-driver = {path = "../driver", version = "^0.24.0"}
test-files = {path = "../test-files", package = "fe-test-files" }
hex = "0.4"
primitive-types = {version = "0.12", default-features = false, features = ["rlp"]}
rand = "0.8.5"
rstest = "0.6.4"
# This fork contains the shorthand macros and some other necessary updates.
yultsur = {git = "https://github.com/fe-lang/yultsur", rev = "ae85470"}
insta = { default-features = false, version = "1.26" }
pretty_assertions = "1.0.0"
wasm-bindgen-test = "0.3.24"
dir-test="0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
proptest = {version = "1.1.0", default-features = false, features = ["std"]}

[features]
solc-backend = ["fe-yulc/solc-backend", "fe-compiler-test-utils/solc-backend"]
