[book]
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
language = "en"
multilingual = false
src = "src"
title = "The Fe Guide"

[output.html]
additional-js = ["theme/custom-highlight.js"]
additional-css = ["theme/reference.css"]

[output.linkcheck]
follow-web-links = true
warning-policy = "error"
exclude = [ 'github\.com', 'etherscan\.io', 'goerlifaucet\.com', 'alchemy\.com', 'infura\.io', 'marketplace.visualstudio\.com']

[output.html.fold]
enable = true
level = 1