[tool.towncrier]
# Read https://github.com/ethereum/fe/newsfragments/README.md for instructions
# package = "fe"
filename = "docs/src/release_notes.md"
directory = "newsfragments"
underlines = ["", ""]
issue_format = "[#{issue}](https://github.com/ethereum/fe/issues/{issue})"
start_string = "[//]: # (towncrier release notes start)"
title_format = "## {version} ({project_date})"

[[tool.towncrier.type]]
directory = "feature"
name = "### Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "### Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "performance"
name = "### Performance improvements"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "### Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "### Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "internal"
name = "### Internal Changes - for Fe Contributors"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "### Miscellaneous changes"
showcontent = false