[package]
name = "fe-yulc"
version = "0.24.0"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/ethereum/fe"

[dependencies]
# This fork supports concurrent compilation, which is required for Rust tests.
solc = { git = "https://github.com/fe-lang/solc-rust", rev = "bde551e", optional = true}
serde_json = "1.0"
indexmap = "1.6.2"

[features]
solc-backend = ["solc"]
