[package]
name = "fe-library"
version = "0.24.0"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"

[dependencies]
include_dir = "0.7.2"
indexmap = "1.6.2"
smol_str = "0.1.21"
